name: 'Robot Framework Lint'
description: 'Run lint for Robot Framework'
branding:
  icon: 'check-square'  
  color: 'green'
  
inputs:
  robot-files:
    description: 'The source (.robot) file'
    required: true
    
  configure-rule:
    description: 'Configure a rule'
    required: false    
   
  recursively:
    description: 'Recursively scan subfolders in a directory'
    required: false  
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.robot-files }}
     
     
     
     
