name: 'Robot Framework Lint'
description: 'Run lint for Robot Framework'
branding:
  icon: 'check-square'  
  color: 'green'
  
- uses: actions/checkout@v2
- name: Set up Python
  uses: actions/setup-python@v2
  with:
      python-version: '3.x'
- name: Install dependencies
  run: |
     sudo apt-get -y install python3-pip
     pip3 install robotframework-lint
            
- name: Execute Lint
  - run: |
    # make file runnable, might not be necessary
    chmod +x "${{ github.workspace }}/script.sh"
    # run script
    "${{ github.workspace }}/script.sh"
     
     
     
     
