name: 'Robot Framework Lint'
description: 'Run lint for Robot Framework'
branding:
  icon: 'check-square'  
  color: 'green'
  
inputs:
  robot-files:
    description: 'The source (.robot) file'
    required: true
    
  configure-rule:
    description: 'Configure a rule'
    required: false 
    
  ignore-rule:
    description: 'Ignore the given RULENAME'
    required: false  
    
  argument-file:
    description: 'Read arguments from the given file'
    required: false  
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.robot-files }}
    - ${{ inputs.configure-rule }} 
    - ${{ inputs.ignore-rule }} 
    - ${{ inputs.argument-file }} 
     
     
     
